name: Docs

on:
  push:
    branches:
      - main
    paths:
      - '**/*'
      - '!**/.github/workflows/**'

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # https://github.com/mkdocs/mkdocs/issues/2370
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Generate Docs
        run: |
          pip install mkdocs mkdocs-material mkdocs-github-admonitions-plugin Pygments
          ./gradlew dokkaGeneratePublicationHtml
          mkdir -p docs/api
          mv build/dokka/html/* docs/api/

      - name: Copy Repo Contents
        run: |
          cp README.md docs/index.md
          sed -i 's/docs\///' docs/index.md

      - name: Deploy Docs
        run: |
          mkdocs gh-deploy

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write
